@token=a@a.com12

### Get all products
GET http://localhost:3001/products?categories=ax,Accessories
Authorization: Bearer {{token}}


### Get all products with filter text
GET http://localhost:3001/products/public?storeid=1
Authorization: Bearer {{token}}

### Get all products with store filter
GET http://localhost:3001/products/public?textfilter=Product
Authorization: Bearer {{token}}


####
GET http://localhost:3001/products/
Authorization: Bearer {{token}}
####
GET http://localhost:3001/products/public?page=1&pagelength=2
Authorization: Bearer {{token}}

### Get products by id
GET http://localhost:3001/products/1
Authorization: Bearer {{token}}

### Get all products
GET http://localhost:3001/products/
Authorization: Bearer {{token}}


### Get products by id
GET http://localhost:3001/products/1
Authorization: Bearer {{token}}

### Follow requests filter by store

### Get all products
GET http://localhost:3001/stores/1/products
Authorization: Bearer {{token}}


### Get by id
GET http://localhost:3001/stores/1/products/2
Authorization: Bearer {{token}}



### Create a product
POST http://localhost:3001/stores/1/products/
Content-Type: application/json
Authorization: Bearer {{token}}

{
			"code": "f230fh0g3",
			"name": "Bamboo Watch",
			"description": "Product Description",
			"image": "bamboo-watch.jpg",
			"price": 65,
			"category": "Accessories",
			"quantity": 24,
			"inventoryStatus": "OUTOFSTOCK",
			"rating": 5,
			"currency":"€"
}

### Update a product
PATCH  http://localhost:3001/stores/1/products/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"name changed",
	"price":89
}

### Delete a product
DELETE http://localhost:3001/stores/1/products/1
Authorization: Bearer {{token}}


### Signup
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
    "email":"testalos7",
    "password":"1777"
}

### Login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email":"testalos7",
    "password":"1777"
}