@token=a@a.com12

### Get all stores
GET http://localhost:3001/stores/
Authorization: Bearer {{token}}


### Get by id
GET http://localhost:3001/stores/2
Authorization: Bearer {{token}}



### Create a store
POST http://localhost:3001/stores
Content-Type: application/json
Authorization: Bearer {{token}}

{
      "name": "Toulouse store3",
      "currency": "EUR",
      "address": {
        "streetNumber": "0",
        "streetName": "Street Name",
        "city": "City",
        "state": "State",
        "zipCode": "31000"
      },
      "location": {
        "latitude": 1,
        "longitude": 2
      },
      "contactPhone": "+33 123456",
      "products": [],
      "imageUrl": "https://img.freepik.com/vector-premium/fachada-tienda-plana-toldo_23-2147542588.jpg"
}

### Update a store
PATCH http://localhost:3001/stores/1
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "name":"name change"
}

### Delete a store
DELETE http://localhost:3001/stores/1
Authorization: Bearer {{token}}


